// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaLMBg9Q0nCMgo_jvGWKDeXPIS_cgHvxk',
    appId: '1:1561871725:web:dff9453c56f11b81a8c664',
    messagingSenderId: '1561871725',
    projectId: 'restaurant-menu-system-fc074',
    authDomain: 'restaurant-menu-system-fc074.firebaseapp.com',
    storageBucket: 'restaurant-menu-system-fc074.firebasestorage.app',
    measurementId: 'G-9D1M3Y7GJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUW2EaowUy3QDoRxvEd_b9dK5RqfiD7sw',
    appId: '1:1561871725:android:a54020474518710ea8c664',
    messagingSenderId: '1561871725',
    projectId: 'restaurant-menu-system-fc074',
    storageBucket: 'restaurant-menu-system-fc074.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Oznvpl6DhyvElkyfCdOUYFH5SZwF3Ps',
    appId: '1:1561871725:ios:a4838fb88ce0ebcaa8c664',
    messagingSenderId: '1561871725',
    projectId: 'restaurant-menu-system-fc074',
    storageBucket: 'restaurant-menu-system-fc074.firebasestorage.app',
    iosBundleId: 'com.example.restaurantAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Oznvpl6DhyvElkyfCdOUYFH5SZwF3Ps',
    appId: '1:1561871725:ios:a4838fb88ce0ebcaa8c664',
    messagingSenderId: '1561871725',
    projectId: 'restaurant-menu-system-fc074',
    storageBucket: 'restaurant-menu-system-fc074.firebasestorage.app',
    iosBundleId: 'com.example.restaurantAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaLMBg9Q0nCMgo_jvGWKDeXPIS_cgHvxk',
    appId: '1:1561871725:web:8d37086942cc1bdfa8c664',
    messagingSenderId: '1561871725',
    projectId: 'restaurant-menu-system-fc074',
    authDomain: 'restaurant-menu-system-fc074.firebaseapp.com',
    storageBucket: 'restaurant-menu-system-fc074.firebasestorage.app',
    measurementId: 'G-JWS0HXM50L',
  );
}
